### ISSUE TITLE
How to use getConfig?

### ISSUE THREAD

**Issue by HellScre4m** [rubenlagus/TelegramApi#10]
Hi. I want to only execute getConfig and get its results. I don't want to getting involved to other processes as much as possible. Can you guide me? Much appreciated.

**Comment by rubenlagus** [comment]
getConfig? What do you mean?

**Comment by HellScre4m** [comment]
https://core.telegram.org/method/help.getConfig

**Comment by rubenlagus** [comment]
It is just a single api method, you can execute it using [doRpcCall*](https://github.com/rubenlagus/TelegramApi/blob/51713e9b6eb9e0ae0d4bbbe3d4deffff9b7f01e4/src/main/java/org/telegram/bot/kernel/KernelComm.java) methods

**Comment by HellScre4m** [comment]
Thanks a lot 👍
