### ISSUE TITLE
update to layer 62

### ISSUE THREAD

**Issue by amin1softco** [rubenlagus/TelegramApi#11]
hi 
plz update to last layer 62
tnx

**Comment by danog** [comment]
I don't think this layer exists yet. The current layer version on webogram and tdesktop is 57

**Comment by amin1softco** [comment]
really current layer is 61 😄 but maybe not public for now you can see this in last release of android app
  public static final int LAYER = 61;

**Comment by rubenlagus** [comment]
There is no need to open a bug to update layer, I know it is not in last version and I'll update it when I have the time needed for that

**Comment by amin1softco** [comment]
really telegram is closed source?

**Comment by amin1softco** [comment]
telegram add some payment method in schema71 pl update this library tnx.

**Comment by amin1softco** [comment]
telegram added search users in channel 
``
channelParticipantsSearch#656ac4b
``
plz update this library tnx.
