### ISSUE TITLE
get error while use TLRequestMessageGetHistory

### ISSUE THREAD

**Issue by mehdi1602** [rubenlagus/TelegramApi#12]
I used as below

                TLRequestMessagesGetHistory tlReq = new TLRequestMessagesGetHistory();
                TLAbsInputPeer _peer = (TLAbsInputPeer) new TLInputPeerChat();
                ((TLInputPeerChat) _peer).setChatId(update.getChannelId()); 
                tlReq.setPeer(_peer);
                TLAbsMessages messagesEx = kernelComm.getApi().doRpcCall(tlReq);`
but all the time i get exceptions INVALID_CHANNEL_ID or INVALID_CHAT_ID

          ` org.telegram.api.engine.RpcException: CHAT_ID_INVALID`
could you please help me to know why I get this error?

**Comment by rubenlagus** [comment]
If you want to get the history from a channel, you need to use inputpeerchannel, not inputpeerchat.
