### ISSUE TITLE
how to get list of already joind channels or groups

### ISSUE THREAD

**Issue by mehdi1602** [rubenlagus/TelegramApi#14]
Hi Guys,
the client calls onChat function in the ChatHandeler for a lot of chats. I want to know wheter I already joined to a chat (channel or group) or not?
or equally is there any way to have a list of group and channels that i have joined already?

**Comment by fbotis** [comment]
TLRequestMessagesGetDialogs getDialogs = new TLRequestMessagesGetDialogs();
 getDialogs.setOffsetPeer(new TLInputPeerSelf());
 TLAbsDialogs dialogs = api.doRpcCall(getDialogs);
  for (TLAbsChat c : dialogs.getChats()) {
     ....

**Comment by mehdi1602** [comment]
thank you @fbotis but your code sometimes returns channels that I have not joined yet.
I want a list of all channels that I have joined.

**Comment by rubenlagus** [comment]
@fbotis request will only return those channels that you actually join, aka those channels that you will see in any of the telegram app.
