### ISSUE TITLE
is this already updated to layer 57?

### ISSUE THREAD

**Issue by viperpix** [rubenlagus/TelegramApi#16]
is it or i should make some changes to be able to use it on layer 57?

and how can i convert schema.tl into java source files? is there any instructions or tool or something?

Thank you alot.

**Comment by viperpix** [comment]
also im facing an Error While Saving Stat files :

java.io.NotSerializableException: org.telegram.bot.kernel.engine.MemoryApiState
	at java.io.ObjectOutputStream.writeObject0(Unknown Source)
	at java.io.ObjectOutputStream.writeObject(Unknown Source)

=> and if i add serializable to MemoryApiState, it works without an error but the output file is corrupted
please help, thank you

**Comment by rubenlagus** [comment]
No, and doubt it will be done for layer 57. Quite probably it will jump to further layer when updated.
