### ISSUE TITLE
400 API_ID_INVALID error

### ISSUE THREAD

**Issue by astuteficus** [rubenlagus/TelegramApi#21]
I've got here (https://my.telegram.org/apps) API_ID, API_HASH,  IP and port of DC I should use.
I set everything corectly, but anyway get 400 API_ID_INVALID error using TLRequestAuthSendCode.

**Comment by astuteficus** [comment]
Works with another AipId (obtained a long time ago). So it's Telegram's issue

**Comment by shekoofev** [comment]
for me, I removed ' ' of appID and it worked.😍💃
