### ISSUE TITLE
Cannot connect to API

### ISSUE THREAD

**Issue by luzzif** [rubenlagus/TelegramApi#35]
So far I've implemented the `AbsApiState`, but I cannot connect to the API. This is the class:

<code>
    package com.github.luzzif.telegram;

    import org.springframework.beans.factory.annotation.Value;
    import org.springframework.stereotype.Component;
    import org.telegram.api.TLConfig;
    import org.telegram.api.TLDcOption;
    import org.telegram.api.auth.TLAuthorization;
    import org.telegram.api.engine.storage.AbsApiState;
    import org.telegram.mtproto.state.AbsMTProtoState;
    import org.telegram.mtproto.state.ConnectionInfo;
    import org.telegram.mtproto.state.KnownSalt;

    import java.util.ArrayList;
    import java.util.HashMap;
    import java.util.List;
    import java.util.Map;

    public class ApiState implements AbsApiState {

    private Map< Integer, List< ConnectionInfo > > dataCentersConnectionInfos;
    private Map< Integer, Boolean > dataCentersAutorizhations;
    private Map< Integer, byte[] > authorizationKeys;
    private int primaryDataCenterId;
    private int userId;

    public ApiState( String apiTestIp, String apiProductionIp, boolean test ) {

        primaryDataCenterId = 0;
        dataCentersConnectionInfos = new HashMap<>();
        ConnectionInfo connectionInfo = new ConnectionInfo(
                primaryDataCenterId,
                0,
                test ? apiTestIp : apiProductionIp,
                443
        );
        List< ConnectionInfo > connectionInfos = new ArrayList<>();
        connectionInfos.add( connectionInfo );
        dataCentersConnectionInfos.put( primaryDataCenterId, connectionInfos );

        dataCentersAutorizhations = new HashMap<>();
        dataCentersAutorizhations.put( primaryDataCenterId, false );

        authorizationKeys = new HashMap<>();

    }

    @Override
    public int getPrimaryDc() {
        return primaryDataCenterId;
    }

    @Override
    public void setPrimaryDc( int dataCenterId ) {
        primaryDataCenterId = dataCenterId;
    }

    @Override
    public boolean isAuthenticated() {
        return dataCentersAutorizhations.getOrDefault( primaryDataCenterId, false );

    }

    @Override
    public boolean isAuthenticated( int dataCenterId ) {
        return dataCentersAutorizhations.getOrDefault( dataCenterId, false );
    }

    @Override
    public void setAuthenticated( int dataCenterId, boolean authenticated ) {
        dataCentersAutorizhations.put( dataCenterId, authenticated );
    }

    @Override
    public void updateSettings( TLConfig config ) {

        dataCentersConnectionInfos.clear();
        for( TLDcOption dataCenterInfo : config.getDcOptions() ) {

            int dataCenterId = dataCenterInfo.getId();
            ConnectionInfo connectionInfo = new ConnectionInfo(
                    dataCenterId,
                    0,
                    dataCenterInfo.getIpAddress(),
                    dataCenterInfo.getPort()
            );
            if( dataCentersConnectionInfos.containsKey( dataCenterId ) ) {
                dataCentersConnectionInfos.get(  dataCenterId ).add( connectionInfo );
                continue;
            }
            List< ConnectionInfo > connectionInfos = new ArrayList<>();
            connectionInfos.add( connectionInfo );
            dataCentersConnectionInfos.put( dataCenterId, connectionInfos );

        }

    }

    @Override
    public byte[] getAuthKey( int dataCenterId ) {
        return authorizationKeys.getOrDefault( dataCenterId, new byte[ 0 ] );
    }

    @Override
    public void putAuthKey( int dataCenterId, byte[] authorizationKey ) {
        authorizationKeys.put( dataCenterId, authorizationKey );
    }

    @Override
    public ConnectionInfo[] getAvailableConnections( int dataCenterId ) {

        List< ConnectionInfo > connectionInfos =
                dataCentersConnectionInfos.getOrDefault( dataCenterId, new ArrayList<>() );
        return connectionInfos.toArray( new ConnectionInfo[ connectionInfos.size() ] );

    }

    @Override
    public synchronized AbsMTProtoState getMtProtoState( int dataCenterId ) {

        return new AbsMTProtoState() {

            private KnownSalt[] knownSalts = new KnownSalt[ 0 ];

            @Override
            public byte[] getAuthKey() {
                return ApiState.this.getAuthKey( dataCenterId );
            }

            @Override
            public ConnectionInfo[] getAvailableConnections() {
                return ApiState.this.getAvailableConnections( dataCenterId );
            }

            @Override
            public KnownSalt[] readKnownSalts() {
                return knownSalts;
            }

            @Override
            protected void writeKnownSalts(KnownSalt[] salts) {
                knownSalts = salts;
            }
        };

    }

    @Override
    public void doAuth( TLAuthorization authorization ) {
        userId = authorization.getUser().getId();
    }

    @Override
    public void resetAuth() {
        dataCentersAutorizhations.clear();
    }

    @Override
    public void reset() {
        dataCentersAutorizhations.clear();
        authorizationKeys.clear();
    }

    @Override
    public int getUserId() {
        return userId;
    }

    }

Attached we have the stack trace of the error

    Exception in thread "Scheduller#1222289141" java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at org.telegram.mtproto.secure.CryptoUtils.substring(CryptoUtils.java:249)
	at org.telegram.mtproto.MTProto.encrypt(MTProto.java:520)
	at org.telegram.mtproto.MTProto.access$1100(MTProto.java:45)
	at org.telegram.mtproto.MTProto$SchedullerThread.run(MTProto.java:727)

**Comment by gnauq3mg6m64rs2n** [comment]
How to fix an error?
