### ISSUE TITLE
How to use deserializeBody function?

### ISSUE THREAD

**Issue by pazis** [rubenlagus/TelegramApi#4]
I want to download media from the message and it seems that I have to deserializeBody first to get the access hash. Well, the function gets two arguments: `InputStream` and `TLContext`. I have no idea what to send as argument! Can you help me with this?

for example for photos the function is:

```
@Override
    public void deserializeBody(InputStream stream, TLContext context)
            throws IOException {
        this.photo = ((TLAbsPhoto) StreamingUtils.readTLObject(stream, context));
        this.caption = StreamingUtils.readTLString(stream);
    }
```

but no example to learn what the arguments should be.

thanks

**Comment by rubenlagus** [comment]
That method is not supposed to be used externally, only by the api itself
