### ISSUE TITLE
TLChannel class is incomplete?

### ISSUE THREAD

**Issue by pazis** [rubenlagus/TelegramApi#5]
I was wondering how to get `channel.isBroadcast()` in a `TLChannel`. Actually it's possible in `TLChannelForbidden`, but not in `TLChannel`. Is it because `TLChannel` class is incomplete or because Telegram doesn't return it in response?

**Comment by pazis** [comment]
20 days passed... no answers... 😢 😭

**Comment by rubenlagus** [comment]
Broadcast are obsolete chats types in Telegram. The getter could be added but it won't be really helpful.

**Comment by pazis** [comment]
how about the other flags?

**Comment by rubenlagus** [comment]
Probably, I add them as I'm needed them. Feel free to make a pull request with one of them if you need it in any object

**Comment by pazis** [comment]
OK. thanks.
