### ISSUE TITLE
Where is the documentation for this library?

### ISSUE THREAD

**Issue by alexandr-grinev** [rubenlagus/TelegramApi#58]
I could not find any documentation for the library. Please help me save time, tell me where can I find the any documentation for the library?

**Comment by sadeghpro** [comment]
use [Deepthought](https://github.com/rubenlagus/Deepthought) example code

**Comment by alexandr-grinev** [comment]
@sadeghpro Thanks for answer. 
I used this project as an example and indeed, for a quick start he helped me a lot.

To the library author: use the factory method or the constructor with the mandatory parameters to create the TLRequest* objects. This would greatly simplify the creation of TLRequest* objects. Plus, the TLRequest* objects must be immutable.

Thanks for library !
