### ISSUE TITLE
Where to find description of DefaultUpdatesHandler functions?

### ISSUE THREAD

**Issue by pazis** [rubenlagus/TelegramApi#6]
Well, there are a lot of functions in `DefaultUpdatesHandler` to be overriden, but it's so hard to correctly guess what they do based on their names. How can I find a brief description of what each function does? 👶 🍼

**Comment by rubenlagus** [comment]
same way as I do: test-error

**Comment by pazis** [comment]
Telegram guys are awesome at documentation :face_with_head_bandage:
