### ISSUE TITLE
How to join a group or channel by link?

### ISSUE THREAD

**Issue by pazis** [rubenlagus/TelegramApi#7]
Well, guess I have a group or channel link. Any example or help on how to join it?

**Comment by pazis** [comment]
I can join a group or channel by its ID and accessHash like this:

        TLRequestChannelsJoinChannel join = new TLRequestChannelsJoinChannel();
        TLInputChannel ch = new TLInputChannel();
        ch.setChannelId(1001497991);
        ch.setAccessHash(-8458340302386176228l);
        join.setChannel(ch);
        try {
            TLAbsUpdates bb = kernelComm.getApi().doRpcCall(join);
        } catch (IOException e) {
            e.printStackTrace();
        } catch (TimeoutException e) {
            e.printStackTrace();
        }

Is it right? How can I join via the link?

**Comment by pazis** [comment]
I found out how to get channel ID from the username, too, but still don't know how to get the access hash.

        TLRequestContactsResolveUsername res = new TLRequestContactsResolveUsername();
        res.setUsername("channelusernamehere");
        try {
            TLResolvedPeer pe = kernelComm.getApi().doRpcCall(res);
            pe.getId();
        } catch (IOException e) {
            e.printStackTrace();
        } catch (TimeoutException e) {
            e.printStackTrace();
        }

**Comment by rubenlagus** [comment]
Have a look to `messages.checkChatInvite#3eadb1bb hash:string = ChatInvite;` in schema

**Comment by pazis** [comment]
For fellow readers, here is the code to join groups/channels by link:

    for (String str : links){
                if (str.contains("telegram.me/joinchat")){
                    String hash = str.split("/")[(str.split("/").length)-1];
                        TLRequestMessagesImportChatInvite in = new TLRequestMessagesImportChatInvite();
                        in.setHash(hash);
                        try {
                            TLAbsUpdates bb = kernelComm.getApi().doRpcCall(in);
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                } else if (str.contains("telegram.me/")){
                    String username = str.split("/")[(str.split("/").length)-1];
                        try {
                            TLRequestContactsResolveUsername ru = new TLRequestContactsResolveUsername();
                            ru.setUsername(username);
                            TLResolvedPeer peer = kernelComm.getApi().doRpcCall(ru);
                            TLRequestChannelsJoinChannel join = new TLRequestChannelsJoinChannel();
                            TLInputChannel ch = new TLInputChannel();
                            ch.setChannelId(peer.getChats().get(0).getId());
                            ch.setAccessHash(((TLChannel) peer.getChats().get(0)).getAccessHash());
                            join.setChannel(ch);
                            kernelComm.getApi().doRpcCall(join);
                        } catch (Exception e) {
                            e.printStackTrace();
                        } 
                }
            }

**Comment by edbrik** [comment]
what is links??

`for (String str : links){`

**Comment by pazis** [comment]
@edbrik it's a list of links like http://telegram.me/hoko_ir

**Comment by A7F** [comment]
> TLAbsUpdates bb = kernelComm.getApi().doRpcCall(in);
How do you know that doRpcCall method return a TLAbsUpdates object? Let's say I want to get the chat invite link inside the group I made, if I send a TLRequestMessagesExportChatInvite then what should I expect back to get the link when doing the rpcCall?

**Comment by hosseinGanjyar** [comment]
Hi ervery body, How I can join to group using by just link. for example:
https://telegram.me/joinchat/A3hpsDwTGnR6I8sD9C1kcA

**Comment by spooksie** [comment]
@hosseinGanjyar 

`from telethon.tl.functions.messages import ImportChatInviteRequest`
`updates = client(ImportChatInviteRequest('A3hpsDwTGnR6I8sD9C1kcA'))`

**Comment by hosseinGanjyar** [comment]
@spooksie thanks, but I usnig [Telesharp library](https://github.com/sochix/TLSharp).

**Comment by Coderwill** [comment]
guys here i have one issue facing on telegram  bot using with c#. i am going send image with caption and in the caption i have one group link. and group create my self in india. i am user from india. and i in my group join one person from canada. and canadian user share this image to her iranian user. and then after iranian user click on link user can not join group on there in the iran. here in india this is working very well. any user click on link he is join our group. so here any one have idea why this type issue getting wit me.

**Comment by amin1softco** [comment]
public link of supergroup only activated in usa and some other region


March 13, 2016
The Telegram Team


> Starting today, supergroups can become public and get a short link, like telegram.me/publictestgroup. This way, anybody can view the group's entire chat history and join to post messages.
.
.
.
P.S. Please note that we’ll be rolling out public groups gradually. They’re already live in Europe and America, but are currently not available in several countries in Asia, from which we detected significant spam activity in the past.

We’ll be making the feature available in more countries as we improve our anti-spam algorithms and scale our abuse team.

**Comment by Coderwill** [comment]
@amin1softco  can you please give me link for this description give some more bit in details information.

**Comment by Coderwill** [comment]
@amin1softco  one more thing here suppose iranian user create group him or her self and i am upload in this group any image and link and image share any user then user will be abale to join group??

**Comment by amin1softco** [comment]
@Coderwill  
link : https://telegram.org/blog/supergroups5k
you can share private one link to solve your problem but maybe after some time expire...

**Comment by Coderwill** [comment]
@amin1softco thank yopu so much for your replay and give me link and suggestion.

**Comment by wwhiteJ** [comment]
@amin1softco , can you please give an example of joining the public group with this api through the short link like https://t.me/XXXXXXXX ?

**Comment by trmazurkevych** [comment]
@wwhiteJ have you found a solution how to join the public group via short link via API?

**Comment by AxDSan** [comment]
I'm trying to find the way to use the `tg://` URI Scheme through an API is that even possible?
