### ISSUE TITLE
How to recieve messages having photos and videos?

### ISSUE THREAD

**Issue by pazis** [rubenlagus/TelegramApi#9]
I've implemented many methods in `DefaultUpdatesHandler` and I recieve none of the messages with a file attached. How can I recieve them?

**Comment by rubenlagus** [comment]
They arrive in normal messages but with Media content

**Comment by pazis** [comment]
Actually I assume that there should be a function with a `TLAbsMessageMedia` as argument, so that I can handle the media content, but there is none.

`TLAbsMessage` cannot be converted to for example `TLMessageMediaPhoto`, so basically I can't handle photo messages in `onTLUpdateNewMessageCustom(TLUpdateNewMessage update)` because `update.getMessage()` is a `TLAbsMessage`. Then when do media messages go!?

**Comment by pazis** [comment]
oh I got it!! `update.getMessage().getMedia()` does it! thanks!

**Comment by mehdi1602** [comment]
hi pazis,
Have you find the way of downloading file?
